# Generated by Django 6.0.4 on 2026-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('deadline_datetime', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('tags', models.ManyToManyField(related_name='tasks', to='todo.tag')),
            ],
        ),
    ]
