# Generated by Django 6.0.4 on 2026-04-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deadline_datetime',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='success',
            new_name='is_done',
        ),
    ]
